import assert from "node:assert/strict";
import { test } from "node:test";
import { FLOW_SCHEMA_VERSION, initialState, reportJson } from "../../dist/index.js";
import { requireSchemaDefFields, requireSchemaFields } from "./helpers/assertions.mjs";
import { json } from "./helpers/fixtures.mjs";

test("schemas describe the runtime contract", async () => {
  const definitionSchema = await json("schemas/flow-definition.schema.json");
  const runSchema = await json("schemas/flow-run.schema.json");
  const evidenceSchema = await json("schemas/gate-evidence.schema.json");
  const reportSchema = await json("schemas/flow-report.schema.json");
  const configSchema = await json("schemas/flow-config.schema.json");
  const configMergeReportSchema = await json("schemas/flow-config-merge-report.schema.json");
  const transitionValidationRequestSchema = await json("schemas/flow-transition-validation-request.schema.json");
  const transitionValidationResultSchema = await json("schemas/flow-transition-validation-result.schema.json");
  const releaseReadinessPolicySchema = await json("schemas/release-readiness-policy.schema.json");
  const releaseReadinessResultSchema = await json("schemas/release-readiness-result.schema.json");
  const versionReleaseReportSchema = await json("schemas/version-release-report.schema.json");

  assert.deepEqual(definitionSchema.oneOf, [
    { $ref: "#/$defs/flat_definition" },
    { $ref: "#/$defs/resource_definition" }
  ]);
  assert.equal(definitionSchema.$defs.flat_definition.properties.version.type, "string");
  assert.equal(definitionSchema.$defs.flat_definition.properties.steps.$ref, "#/$defs/steps");
  assert.equal(definitionSchema.$defs.flat_definition.properties.gates.$ref, "#/$defs/gates");
  assert.equal(definitionSchema.$defs.resource_definition.properties.apiVersion.const, "flow.kontourai.io/v1alpha1");
  assert.equal(definitionSchema.$defs.resource_definition.properties.kind.const, "FlowDefinition");
  assert.equal(definitionSchema.$defs.resource_definition.properties.spec.$ref, "#/$defs/resource_spec");
  assert.equal(definitionSchema.$defs.resource_metadata.properties.name.$ref, "#/$defs/definition_name");
  assert.equal(definitionSchema.$defs.resource_metadata.properties.labels.$ref, "#/$defs/resource_string_map");
  assert.equal(definitionSchema.$defs.resource_metadata.properties.annotations.$ref, "#/$defs/resource_string_map");
  assert.equal(definitionSchema.$defs.resource_spec.properties.version.type, "string");
  assert.equal(definitionSchema.$defs.resource_spec.properties.steps.$ref, "#/$defs/steps");
  assert.equal(definitionSchema.$defs.resource_spec.properties.gates.$ref, "#/$defs/gates");
  assert.equal(definitionSchema.$defs.steps.items.$ref, "#/$defs/step");
  assert.equal(definitionSchema.$defs.gates.additionalProperties.$ref, "#/$defs/gate");
  assert.equal(runSchema.title, "Flow Run State");
  assert.match(runSchema.description, /state\.json/);
  assert.match(runSchema.description, /not a Resource Contract envelope/);
  assert.equal(runSchema.properties.schema_version.const, FLOW_SCHEMA_VERSION);
  assert.match(runSchema.properties.run_id.description, /\.flow\/runs\/<run-id>/);
  assert.match(runSchema.properties.current_step.description, /step id/);
  assert.match(runSchema.properties.gate_outcomes.description, /gate decisions/);
  assert.match(runSchema.properties.transitions.description, /route-back attempt counting/);
  assert.equal(evidenceSchema.properties.schema_version.const, FLOW_SCHEMA_VERSION);
  assert.match(evidenceSchema.description, /evidence\/manifest\.json/);
  assert.match(evidenceSchema.description, /standalone scenario manifests may omit/);
  assert.match(evidenceSchema.description, /not an authored Resource Contract/);
  assert.equal(evidenceSchema.properties.run_id.minLength, 1);
  assert.equal(evidenceSchema.properties.definition_id.minLength, 1);
  assert.equal(reportSchema.properties.schema_version.const, FLOW_SCHEMA_VERSION);
  assert.deepEqual(configSchema.oneOf, [
    { $ref: "#/$defs/flat_config" },
    { $ref: "#/$defs/resource_config" }
  ]);
  assert.equal(configSchema.$defs.flat_config.properties.schema_version.const, FLOW_SCHEMA_VERSION);
  assert.equal(configSchema.$defs.flat_config.properties.trusted_producers.$ref, "#/$defs/trusted_producers");
  assert.equal(configSchema.$defs.flat_config.properties.gate_overrides.$ref, "#/$defs/gate_overrides");
  assert.equal(configSchema.$defs.resource_config.properties.apiVersion.const, "flow.kontourai.io/v1alpha1");
  assert.equal(configSchema.$defs.resource_config.properties.kind.const, "FlowProjectConfig");
  assert.equal(configSchema.$defs.resource_config.properties.spec.$ref, "#/$defs/config_spec");
  assert.equal(configSchema.$defs.resource_metadata.properties.name.$ref, "#/$defs/config_name");
  assert.equal(configSchema.$defs.resource_metadata.properties.labels.$ref, "#/$defs/resource_string_map");
  assert.equal(configSchema.$defs.resource_metadata.properties.annotations.$ref, "#/$defs/resource_string_map");
  assert.equal(configSchema.$defs.config_spec.properties.schema_version.const, FLOW_SCHEMA_VERSION);
  assert.equal(configSchema.$defs.config_spec.properties.trusted_producers.$ref, "#/$defs/trusted_producers");
  assert.equal(configSchema.$defs.config_spec.properties.gate_overrides.$ref, "#/$defs/gate_overrides");
  assert.deepEqual(configSchema.$defs.safe_map_key.not.enum, ["__proto__", "prototype", "constructor"]);
  assert.equal(configSchema.$defs.resource_string_map.propertyNames.$ref, "#/$defs/safe_map_key");
  assert.equal(configSchema.$defs.trusted_producers.propertyNames.$ref, "#/$defs/safe_map_key");
  assert.equal(configSchema.$defs.gate_overrides.propertyNames.$ref, "#/$defs/safe_map_key");
  assert.equal(configSchema.$defs.gate_override.properties.expectations.propertyNames.$ref, "#/$defs/safe_map_key");
  assert.equal(configMergeReportSchema.properties.schema_version.const, FLOW_SCHEMA_VERSION);
  assert.equal(configMergeReportSchema.properties.merged_config.$ref, "flow-config.schema.json#/$defs/flat_config");
  assert.equal(transitionValidationRequestSchema.title, "Flow Transition Validation Request");
  assert.equal(transitionValidationRequestSchema.properties.config.$ref, "flow-config.schema.json#/$defs/flat_config");
  assert.equal(transitionValidationResultSchema.title, "Flow Transition Validation Result");
  assert.equal(releaseReadinessPolicySchema.title, "Release Readiness Policy");
  assert.equal(releaseReadinessResultSchema.title, "Release Readiness Result");
  assert.equal(versionReleaseReportSchema.title, "Version Release Report");

  assert.ok(definitionSchema.$defs.gate.properties.on_route_back);
  assert.ok(definitionSchema.$defs.gate.properties.expects);
  assert.equal(definitionSchema.$defs.gate.properties.requires, undefined);
  assert.ok(definitionSchema.$defs.gate.properties.route_back_policy);
  assert.equal(definitionSchema.$defs.gate.properties.route_back_policy.properties.allow_unknown_reasons.type, "boolean");
  assert.ok(evidenceSchema.$defs.evidence.properties.route_reason);
  assert.ok(evidenceSchema.$defs.evidence.properties.trust_artifact);
  assert.equal(evidenceSchema.$defs.evidence.properties.trust_artifact.additionalProperties, false);
  assert.equal(evidenceSchema.$defs.evidence.properties.trust_artifact.properties.claims.items.additionalProperties, false);
  assert.ok(evidenceSchema.$defs.evidence.properties.authority_traces);
  assert.ok(evidenceSchema.$defs.evidence.properties.classifier);
  assert.ok(runSchema.$defs.gate_outcome.properties.route_reason);
  assert.ok(runSchema.$defs.transition.properties.route_reason);
  assert.ok(reportSchema.properties.gate_summaries.items.properties.route_reason);
  assert.ok(reportSchema.properties.gate_summaries.items.properties.selected_route);
  assert.ok(reportSchema.properties.gate_summaries.items.properties.recovery_step);
  assert.ok(reportSchema.properties.gate_summaries.items.properties.analytics_loop_key);
  assert.ok(transitionValidationRequestSchema.properties.definition);
  assert.ok(transitionValidationRequestSchema.properties.current_state);
  assert.ok(transitionValidationRequestSchema.properties.state);
  assert.ok(transitionValidationRequestSchema.properties.proposed_transition);
  assert.ok(transitionValidationRequestSchema.properties.transition);
  assert.ok(transitionValidationRequestSchema.properties.proposed_state);
  assert.ok(transitionValidationRequestSchema.properties.manifest);
  assert.ok(transitionValidationRequestSchema.properties.evidence_refs);
  assert.ok(transitionValidationRequestSchema.properties.config);
  assert.ok(transitionValidationRequestSchema.properties.now);
  assert.ok(transitionValidationResultSchema.properties.valid);
  assert.ok(transitionValidationResultSchema.properties.status);
  assert.ok(transitionValidationResultSchema.properties.diagnostics);
  assert.ok(transitionValidationResultSchema.properties.transition);
  assert.ok(transitionValidationResultSchema.$defs.transition_preview.properties.route_reason);
  assert.ok(transitionValidationResultSchema.$defs.transition_preview.properties.evidence_refs);
  assert.ok(transitionValidationResultSchema.$defs.transition_preview.properties.expectation_ids);
  assert.ok(transitionValidationResultSchema.$defs.transition_preview.properties.classifier);
  assert.ok(transitionValidationResultSchema.$defs.transition_preview.properties.diagnostics);
  assert.ok(transitionValidationResultSchema.$defs.transition_preview.properties.analytics);
  assert.ok(transitionValidationResultSchema.$defs.transition_preview.properties.analytics_loop_key);

  requireSchemaDefFields(definitionSchema, "flat_definition", ["id", "version", "steps", "gates"]);
  requireSchemaDefFields(definitionSchema, "resource_definition", ["apiVersion", "kind", "metadata", "spec"]);
  requireSchemaDefFields(definitionSchema, "resource_metadata", ["name"]);
  requireSchemaDefFields(definitionSchema, "resource_spec", ["version", "steps", "gates"]);
  requireSchemaFields(runSchema, ["schema_version", "run_id", "definition_id", "status", "current_step", "gate_outcomes", "transitions", "exceptions"]);
  requireSchemaFields(evidenceSchema, ["schema_version", "evidence"]);
  assert.ok(evidenceSchema.properties.run_id);
  assert.ok(evidenceSchema.properties.definition_id);
  requireSchemaFields(reportSchema, ["schema_version", "run_id", "definition_id", "status", "summary", "current_step", "gate_summaries"]);
  requireSchemaDefFields(configSchema, "flat_config", ["schema_version"]);
  requireSchemaDefFields(configSchema, "resource_config", ["apiVersion", "kind", "metadata", "spec"]);
  requireSchemaDefFields(configSchema, "resource_metadata", ["name"]);
  requireSchemaDefFields(configSchema, "config_spec", ["schema_version"]);
  requireSchemaFields(configMergeReportSchema, ["schema_version", "mode", "status", "local_config_path", "proposal_path", "proposed_changes", "accepted_changes", "rejected_changes", "conflicts", "unchanged", "exceptions", "merged_config", "summary"]);
  requireSchemaFields(transitionValidationRequestSchema, ["definition"]);
  requireSchemaFields(transitionValidationResultSchema, ["valid", "status", "diagnostics", "transition"]);
  requireSchemaFields(releaseReadinessPolicySchema, ["schema_version", "id", "lanes", "risk_classes"]);
  requireSchemaFields(releaseReadinessResultSchema, ["schema_version", "policy_id", "decision", "risk_class", "subject", "required_lanes", "lanes", "evidence", "report_data"]);
  requireSchemaFields(versionReleaseReportSchema, ["schema_version", "version", "subject", "decision", "status", "summary", "changeset", "verification_evidence", "release_evidence", "exceptions", "accepted_risks", "gaps", "external_links", "native_refs", "report_data"]);
  assert.ok(configMergeReportSchema.$defs.change.properties.path);
  assert.ok(configMergeReportSchema.$defs.change.properties.section);
  assert.ok(configMergeReportSchema.$defs.change.properties.local_value);
  assert.ok(releaseReadinessPolicySchema.$defs.lane.properties.claim.properties.accepted_statuses);
  assert.deepEqual(releaseReadinessResultSchema.$defs.lane_outcome.properties.status.enum, ["pass", "hold", "not_required", "not_verified"]);
  assert.ok(releaseReadinessResultSchema.$defs.lane_outcome.properties.external_links);
  assert.ok(releaseReadinessResultSchema.$defs.lane_outcome.properties.native_refs);
  assert.deepEqual(versionReleaseReportSchema.properties.decision.enum, ["ready", "hold"]);
  assert.equal(versionReleaseReportSchema.properties.release_evidence.$ref, "release-readiness-result.schema.json");
  assert.deepEqual(versionReleaseReportSchema.$defs.gap.properties.kind.enum, ["verification_evidence", "release_lane"]);
});

test("runtime-generated run and report satisfy required schema fields", async () => {
  const definition = await json("examples/agent-dev-flow.json");
  const state = initialState(definition, "schema-check", { subject: "feature-search-filters" });
  const report = reportJson(definition, state, { schema_version: FLOW_SCHEMA_VERSION, evidence: [] });
  assert.equal(state.schema_version, FLOW_SCHEMA_VERSION);
  assert.equal(state.definition_id, definition.id);
  assert.equal(report.schema_version, FLOW_SCHEMA_VERSION);
  assert.equal(report.definition_id, definition.id);
});
